version: '3.8'

services:
  # Frontend - Next.js Application
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - '8080:3000'
    environment:
      NODE_ENV: production
      BACKEND_URL: http://ankur-backend:3001
    depends_on:
      - backend
    restart: unless-stopped
    container_name: ankur-frontend
    networks:
      - ankur-network

  # Backend - Database & API
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - '3001:3001'
    environment:
      NODE_ENV: production
      DATABASE_URL: file:/app/backend/prisma/dev.db
    volumes:
      - ankur-db-data:/app/backend/prisma
    restart: unless-stopped
    container_name: ankur-backend
    networks:
      - ankur-network

networks:
  ankur-network:
    driver: bridge

volumes:
  ankur-db-data:
    driver: local
    # profiles: ["dev"]
